Fix on no results interaction not working
bettyblocks/material-ui-component-set pull request #1001
Opened 2021-03-16 15:09 UTC by garethloot

- onNoResults interaction fix fox dataList, dataTable, autocomplete and select

2021-03-16 15:16 UTC, benjamin-rocks approved these changes

2021-03-16 16:24 UTC, jeroenreijs requested changes
Please remove the package.lock.json

2021-03-16 16:35 UTC, garethloot commented
Yes done

2021-03-16 16:39 UTC, jeroenreijs approved these changes

2021-03-16 16:39 UTC, merged

2021-03-18 12:56 UTC, BarryBlocks commented
You can find the status of the linked ticket here: https://bettyblocks.atlassian.net/browse/TA-2377