fix: remove duplicate icons
bettyblocks/material-ui-component-set pull request #3002
Opened 2023-05-09 13:10 UTC by BettyBrian

2023-05-11 16:25 UTC, robbertruiter requested changes

2023-05-11 16:25 UTC, robbertruiter commented on .github/workflows/publish_bundle_acceptance.yml
> +      AZURE_BLOB_ACCOUNT: ${{ secrets.AZURE_BLOB_ACCOUNT_EDGE }}
Is it intentional to use the Azure blob account secret for edge while being in the pulbish_budnle_acceptance?

2023-05-22 06:47 UTC, SanderVanRiessen requested changes

2023-05-22 07:02 UTC, SanderVanRiessen requested changes
The CLI version in the package json needs to be up to date.

2023-05-22 07:42 UTC, SanderVanRiessen approved these changes

2023-05-22 07:42 UTC, merged