fix: replaced hardcoded disabled kinds
bettyblocks/material-ui-component-set pull request #3067
Opened 2023-06-05 14:15 UTC by LennonStolkBB

2023-06-06 09:26 UTC, Christiaan-Bruin requested changes

2023-06-06 09:26 UTC, Christiaan-Bruin commented on src/prefabs/backOffice.tsx
> +  const searchPropDisabledKinds = createBlacklist([
Google doc and login token should probably not be whitelisted

2023-06-06 09:26 UTC, Christiaan-Bruin commented on src/prefabs/backOffice.tsx
> +  const dataTablePropertiesDisabledKinds = createBlacklist([
Same here, in addition to password and file props

2023-06-06 09:26 UTC, Christiaan-Bruin commented on src/prefabs/backOffice.tsx
> +  const formPropertiesDisabledKinds = createBlacklist([
same here

2023-06-06 09:26 UTC, Christiaan-Bruin commented on src/prefabs/backOffice.tsx
> +  const searchPropDisabledKinds = createBlacklist([
I don't think it is possible to use the Object property in the beforeCreate as well

2023-06-06 09:26 UTC, Christiaan-Bruin commented on src/prefabs/pageWithCrudDialogs.tsx
> +  const disabledKinds = createBlacklist([
login token should probably not have to be whitelisted here, object property likely not supported yet as well

2023-06-06 09:26 UTC, Christiaan-Bruin commented on src/prefabs/pageWithCrudSlideOutPanel.tsx
> +  const disabledKinds = createBlacklist([
login token should probably not have to be whitelisted here, object property likely not supported yet as well

2023-06-06 09:26 UTC, Christiaan-Bruin commented on src/prefabs/pageWithLoginAndRegisterForm.tsx
> +  const disabledKinds = createBlacklist([
Login token / Object property should probably not be whitelisted here

2023-06-06 09:26 UTC, Christiaan-Bruin commented on src/prefabs/pageWithOverviewAndDetials.tsx
> +  const disabledKinds = createBlacklist([
Login token, password should definitely not be whitelisted here. Object property as well because it doesn't work

2023-06-06 09:26 UTC, Christiaan-Bruin commented on src/prefabs/pageWithProfile.tsx
> +  const profilePictureDisabledKinds = createBlacklist([
Why enable Login token and google document here? Also, object property not supported yet

2023-06-06 09:26 UTC, Christiaan-Bruin commented on src/prefabs/pageWithProfile.tsx
> +  const profileNameDisabledKinds = createBlacklist([
Some of these whitelisted props make no sense: Login token, google document, etc. Also remove object property here

2023-06-06 09:26 UTC, Christiaan-Bruin commented on src/prefabs/pageWithProfile.tsx
> +  const profilePropertiesDisabledKinds = createBlacklist([
Object and Login token can be removed here

2023-06-06 09:26 UTC, Christiaan-Bruin commented on src/prefabs/pageWithRegisterForm.tsx
> +  const disabledKinds = createBlacklist([
Object and login token can be removed here

2023-06-06 09:26 UTC, Christiaan-Bruin commented on src/prefabs/pageWithSimpleDashboard.tsx
> +  const disabledKinds = createBlacklist([
Login token, password and object can be removed here

2023-06-06 09:26 UTC, Christiaan-Bruin commented on src/prefabs/updateForm.tsx
> +  const disabledKinds = createBlacklist([
This one looks pretty good, good job ;P

2023-06-06 11:14 UTC, Christiaan-Bruin commented on src/prefabs/backOffice.tsx
> +  const dataTablePropertiesDisabledKinds = createBlacklist([
My bad

2023-06-07 08:41 UTC, sventruschel approved these changes

2023-06-07 08:46 UTC, Christiaan-Bruin approved these changes

2023-06-07 08:46 UTC, merged