feat: page with master detail view
bettyblocks/material-ui-component-set pull request #966
Opened 2021-02-26 12:00 UTC by Reinier1982

2021-02-26 15:25 UTC, flaviumariean submitted a review, later dismissed

2021-03-05 15:41 UTC, BarryBlocks commented
I've created a ticket on the backlog of team Governators to have this reviewed soon: https://bettyblocks.atlassian.net/browse/TA-2345

2021-04-23 08:23 UTC, jeroenreijs commented on src/prefabs/pageWithMasterDetailView.js
> +                      configuration: {
Can you use the `iconConfiguration` here? It'll save over 200 lines.

2021-04-23 08:23 UTC, jeroenreijs requested changes
See my comment about using the `iconConfiguration`

2021-05-26 08:20 UTC, closed without merging